### ISSUE TITLE
Localhost not displaying Jupyter Examples

### ISSUE THREAD

**Issue by tgd15** [radxtools/collageradiomics#44]
When running the Docker image, my localhost does not display the Jupyter examples. [Click here](https://drive.google.com/file/d/1R1y1hwTjb372TyOT9uohsHDRKHPhOrDv/view?usp=sharing) to see a screenshot of my localhost page.

**Version Information**
macOS 10.15.5
Docker 2.3.0.3
localhost port: 8888
Git 2.24.3 (Apple Git-128)

**Steps to re-create problem**
`Toms-Work-MacBook-Pro:Collageradiomics Tom$ git clone https://github.com/ccipd/collageradiomics.git

Cloning into 'collageradiomics'...
remote: Enumerating objects: 165, done.
remote: Counting objects: 100% (165/165), done.
remote: Compressing objects: 100% (65/65), done.
remote: Total 496 (delta 88), reused 155 (delta 85), pack-reused 331
Receiving objects: 100% (496/496), 1.88 MiB | 1.39 MiB/s, done.
Resolving deltas: 100% (246/246), done.

Toms-Work-MacBook-Pro:Collageradiomics Tom$ cd collageradiomics/
Toms-Work-MacBook-Pro:collageradiomics Tom$ ls -l

total 96
-rw-------  1 Tom  staff   1463 Jun 29 16:05 LICENSE
-rw-------  1 Tom  staff  26476 Jun 29 16:05 README.md
drwx------  3 Tom  staff   4096 Jun 29 16:05 docker
drwx------  3 Tom  staff   4096 Jun 29 16:05 jupyter
drwx------  2 Tom  staff   4096 Jun 29 16:05 module
drwx------  2 Tom  staff   4096 Jun 29 16:05 sample_data

Toms-Work-MacBook-Pro:collageradiomics Tom$ docker pull ccipd/collageradiomics-examples:latest

latest: Pulling from ccipd/collageradiomics-examples
Digest: sha256:896e3daabb23f5813ad271374a8d302283141fbb18afd0a29903c83e1903aae3
Status: Image is up to date for ccipd/collageradiomics-examples:latest
docker.io/ccipd/collageradiomics-examples:latest

Toms-Work-MacBook-Pro:collageradiomics Tom$ docker run -it -p 8888:8888 -v /root ccipd/collageradiomics-examples

[I 20:06:06.315 NotebookApp] Writing notebook server cookie secret to /tmp/notebook_cookie_secret
[W 20:06:06.473 NotebookApp] All authentication is disabled.  Anyone who can connect to this server will be able to run code.
[I 20:06:06.477 NotebookApp] Serving notebooks from local directory: /root
[I 20:06:06.477 NotebookApp] The Jupyter Notebook is running at:
[I 20:06:06.477 NotebookApp] http://fc0e20af3a6c:8888/
[I 20:06:06.477 NotebookApp] Use Control-C to stop this server and shut down all kernels (twice to skip confirmation).`

**Comment by nathanhillyer** [comment]
Hi Tom,

When you go to localhost:8888 in your web browser, what does it show?

**Comment by nathanhillyer** [comment]
Hi Tom,

I requested access to the screenshot you linked above. Cheers.

**Comment by tgd15** [comment]
Hi Nathan,

I just granted you access. Please let me know if you still cannot access it.

Thank you so much!


Tom DeSilvio
tgd15@case.edu
INVent Lab Intern
https://www.linkedin.com/in/thomas-desilvio/ <https://www.linkedin.com/in/thomas-desilvio/>
Personal Website <https://tomdesilvio.com/>

**Comment by tgd15** [comment]
![Screen Shot 2020-06-29 at 4 14 30 PM](https://user-images.githubusercontent.com/67032884/86188141-ad9cf300-bb0b-11ea-879b-68eda7895b72.png)

**Comment by nathanhillyer** [comment]
@tgd15 Thank you, I'll look into this soon!

**Comment by robtoth** [comment]
I believe the command docker `run -it -p 8888:8888 -v /root ccipd/collageradiomics-examples` and the `-v /root` is not exactly correct for mounting the current folder.

@tgd15 if you look at https://docs.docker.com/docker-for-mac/osxfs/ you can see the command is `docker run -it -v ~/Desktop:/Desktop r-base bash`

It appears you may need to do `-v ./:/root` instead of `-v /root`

**Comment by nathanhillyer** [comment]
Can you try: `docker run -it -p 8888:8888 -v $PWD:/root ccipd/collageradiomics-examples`? As Rob pointed out, the console output posted above suggests you may have missed the $PWD: part.

**Comment by nathanhillyer** [comment]
Please reopen this issue if there are still difficulties. Closing for now to clear out milestone issues.
