### ISSUE TITLE
Binary mask needs to be converted into 0 and 255 instead of 0 and 1 to extract features

### ISSUE THREAD

**Issue by pranjalvaidya** [radxtools/collageradiomics#45]
I got an error as:  "Non-contiguous masks are not supported" when the mask values were binary-0 and 1. 
When I changed the values to 0 and 255, the code worked!

**Comment by pranjalvaidya** [comment]
![Capture](https://user-images.githubusercontent.com/35502236/86082942-f51d7380-ba66-11ea-8a0d-ae8e5deb696d.JPG)

**Comment by robtoth** [comment]
@pranjalvaidya should we assume the mask is zero vs non-zero? Is that standard?

**Comment by nathanhillyer** [comment]
Add warning if more than 2 values in binary mask. Also detect if there is no zero values.

**Comment by robtoth** [comment]
Are we yet detecting zero vs non-zero, @nathanhillyer? Or is that still pending?

**Comment by nathanhillyer** [comment]
@nathanhillyer It's done, but not pushed yet.

**Comment by nathanhillyer** [comment]
@robtoth It's done locally, but not pushed yet. Have a slew of changes I'll be getting up today.

**Comment by nathanhillyer** [comment]
@pranjalvaidya This is now fixed. We will support binary masks of 0 and any other value. Please pull the latest docker image and verify on your end.

Thanks for the report!
