### ISSUE TITLE
User documentation

### ISSUE THREAD

**Issue by PrathyushVC** [radxtools/collageradiomics#46]
During the testing of the software I found that the documentation for the syntax specifically the inputs, outputs, and function calls could be clarified in the Documentation section instead of being only in the examples. While I was able to manage using the included examples I believe that a separate section in usage could aid potential users in understanding what and how to use the function more clearly.

**Comment by nathanhillyer** [comment]
Link #10

**Comment by nathanhillyer** [comment]
https://collageradiomics.readthedocs.io/
