### ISSUE TITLE
Documentation Suggestion

### ISSUE THREAD

**Issue by tgd15** [radxtools/collageradiomics#47]
I have a suggestion for the Linux/Mac installation. The documentation states:

> Linux
>[Click here](https://www.docker.com/get-started) and follow the instructions to install Docker.

When you click on the link, it redirected me to Docker’s homepage. Is it supposed to redirect the user to Docker’s homepage or are there supposed to be step-by-step instructions? 

Thanks!

**Comment by nathanhillyer** [comment]
@tgd15 Are you running Ubuntu? We also have instructions for Ubuntu below that doc bullet. We can also add CentOS (https://docs.docker.com/engine/install/centos/), Debian (https://docs.docker.com/engine/install/debian/), and Fedora (https://docs.docker.com/engine/install/fedora/) through packages, and general Linux through binaries (https://docs.docker.com/engine/install/binaries/).

**Comment by tgd15** [comment]
I'm running macOS. Adding the link to the instructions for general Linux through binaries would be helpful. Thanks!
